// Collabix Demo Seed — 150 Sintetik İstifadəçi Profili
// Bütün məlumatlar 100% sintetikdir. Real şəxslərə aid deyil.

/**
 * @typedef {Object} UserProfile
 * @property {string} username
 * @property {string} name
 * @property {string} bio
 * @property {string} profession
 * @property {string} country
 * @property {string} city
 * @property {string} gender - 'k' | 'q'
 * @property {number} age
 * @property {string} group - 'A' | 'B' | 'C' | 'D'
 * @property {Record<string, string>} progLevels
 * @property {Record<string, string>} langLevels
 * @property {string[]} lookingFor
 * @property {string} github
 * @property {string} linkedin
 */

/** @type {UserProfile[]} */
export const USERS = [
  // ═══════════════════════════════════════════════════════
  // GROUP A — Highly Active (18 nəfər)
  // ═══════════════════════════════════════════════════════
  { username: 'turan.dev', name: 'Turan Həsənov', bio: 'Full-stack developer. Next.js, Go, PostgreSQL ilə işləyirəm. Open source həvəskarı.', profession: 'Full-stack Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 27, group: 'A', progLevels: { JavaScript: 'Qabaqcıl', TypeScript: 'Qabaqcıl', Go: 'Orta', SQL: 'Qabaqcıl' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Əməkdaşlıq', 'Open Source'], github: 'turandev', linkedin: '' },
  { username: 'ayla.codes', name: 'Ayla Məmmədova', bio: 'Backend engineer @ startup. Distributed systems, microservices, event-driven architecture.', profession: 'Backend Engineer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 25, group: 'A', progLevels: { Python: 'Qabaqcıl', Go: 'Orta', 'C++': 'Orta', SQL: 'Qabaqcıl' }, langLevels: { İngilis: 'Qabaqcıl', Rus: 'Orta' }, lookingFor: ['Study partner', 'Mentorluq'], github: 'aylacodes', linkedin: '' },
  { username: 'kamran.dev', name: 'Kəmran Əliyev', bio: 'Senior .NET developer. C#, Azure, clean architecture fanatikiyəm. DDD, CQRS tətbiq edirəm.', profession: 'Senior .NET Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 31, group: 'A', progLevels: { 'C#': 'Qabaqcıl', SQL: 'Qabaqcıl', TypeScript: 'Orta' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Əməkdaşlıq'], github: 'kamrandev', linkedin: '' },
  { username: 'nermin.ui', name: 'Nərmin Hüseynli', bio: 'UI/UX designer + frontend developer. Figma, React, accessibility-yə diqqət edirəm.', profession: 'UI/UX Designer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 24, group: 'A', progLevels: { JavaScript: 'Orta', TypeScript: 'Orta', 'HTML/CSS': 'Qabaqcıl' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner', 'Dizayn müzakirəsi'], github: '', linkedin: '' },
  { username: 'elvin.backend', name: 'Elvin Rəhimli', bio: 'Java/Spring Boot developer. Fintech sektorunda 4 il təcrübə. Microservices arxitekturası.', profession: 'Java Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 29, group: 'A', progLevels: { Java: 'Qabaqcıl', Kotlin: 'Orta', SQL: 'Qabaqcıl' }, langLevels: { İngilis: 'Qabaqcıl', Türk: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'elvinbackend', linkedin: '' },
  { username: 'orxan.cloud', name: 'Orxan Nəsirov', bio: 'DevOps engineer. AWS, Terraform, Kubernetes, CI/CD pipeline-lar qururam.', profession: 'DevOps Engineer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 28, group: 'A', progLevels: { Python: 'Orta', Bash: 'Qabaqcıl', Go: 'Başlanğıc' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Əməkdaşlıq', 'Mentorluq'], github: 'orxancloud', linkedin: '' },
  { username: 'sara.design', name: 'Sara Quliyeva', bio: 'Product designer with 5 years of experience. Design systems, user research, prototyping.', profession: 'Product Designer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 26, group: 'A', progLevels: { 'HTML/CSS': 'Qabaqcıl', JavaScript: 'Başlanğıc' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Dizayn müzakirəsi', 'Əməkdaşlıq'], github: '', linkedin: '' },
  { username: 'muradsec', name: 'Murad Vəliyev', bio: 'Cybersecurity researcher. Penetration testing, vulnerability analysis, OWASP Top 10.', profession: 'Security Engineer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 30, group: 'A', progLevels: { Python: 'Qabaqcıl', Bash: 'Qabaqcıl', 'C++': 'Orta' }, langLevels: { İngilis: 'Qabaqcıl', Rus: 'Qabaqcıl' }, lookingFor: ['Security araşdırmaları'], github: 'muradsec', linkedin: '' },
  { username: 'leyla.data', name: 'Leyla İsmayılova', bio: 'Data scientist. Python, TensorFlow, pandas. NLP və computer vision üzrə araşdırmalar aparıram.', profession: 'Data Scientist', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 27, group: 'A', progLevels: { Python: 'Qabaqcıl', SQL: 'Qabaqcıl', 'C++': 'Başlanğıc' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Araşdırma partneri', 'Study partner'], github: 'leyladata', linkedin: '' },
  { username: 'farid.mobile', name: 'Fərid Abbasov', bio: 'Flutter & Swift developer. Cross-platform mobile apps, Firebase integration.', profession: 'Mobile Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 26, group: 'A', progLevels: { Kotlin: 'Qabaqcıl', Swift: 'Qabaqcıl', JavaScript: 'Orta' }, langLevels: { İngilis: 'Orta', Türk: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'faridmobile', linkedin: '' },
  { username: 'gulnar.pm', name: 'Gülnar Bayramova', bio: 'Product manager. Agile, Scrum, roadmap planning. Tech startup təcrübəsi.', profession: 'Product Manager', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 32, group: 'A', progLevels: { SQL: 'Orta', Python: 'Başlanğıc' }, langLevels: { İngilis: 'Qabaqcıl', Alman: 'Başlanğıc' }, lookingFor: ['Əməkdaşlıq', 'Mentorluq'], github: '', linkedin: '' },
  { username: 'alex.rust', name: 'Alex Petrov', bio: 'Systems programmer. Rust, C++, embedded systems. Performance optimization enthusiast.', profession: 'Systems Programmer', country: 'Gürcüstan', city: 'Tbilisi', gender: 'k', age: 29, group: 'A', progLevels: { Rust: 'Qabaqcıl', 'C++': 'Qabaqcıl', Python: 'Orta' }, langLevels: { İngilis: 'Qabaqcıl', Rus: 'Qabaqcıl' }, lookingFor: ['Open Source'], github: 'alexrust', linkedin: '' },
  { username: 'nigar.fe', name: 'Nigar Əliyeva', bio: 'Frontend developer. React, Vue, Svelte — modern framework-lərlə UI qururam.', profession: 'Frontend Developer', country: 'Azərbaycan', city: 'Gəncə', gender: 'q', age: 23, group: 'A', progLevels: { JavaScript: 'Qabaqcıl', TypeScript: 'Qabaqcıl', 'HTML/CSS': 'Qabaqcıl' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: 'nigarfe', linkedin: '' },
  { username: 'rashad.db', name: 'Rəşad Hüseynov', bio: 'DBA + backend developer. PostgreSQL, MySQL, Redis, query optimization mütəxəssisiyəm.', profession: 'Database Engineer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 33, group: 'A', progLevels: { SQL: 'Qabaqcıl', Python: 'Orta', Go: 'Orta' }, langLevels: { İngilis: 'Qabaqcıl', Rus: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'rashaddb', linkedin: '' },
  { username: 'maria.qa', name: 'Maria Kowalski', bio: 'QA engineer. Test automation with Playwright, Cypress. Shift-left testing advocate.', profession: 'QA Engineer', country: 'Polşa', city: 'Varşava', gender: 'q', age: 28, group: 'A', progLevels: { JavaScript: 'Orta', TypeScript: 'Orta', Python: 'Başlanğıc' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Əməkdaşlıq'], github: 'mariaqa', linkedin: '' },
  { username: 'tural.ai', name: 'Tural Məmmədov', bio: 'ML engineer. PyTorch, transformers, LLM fine-tuning. AI tətbiqləri inkişaf etdirirəm.', profession: 'ML Engineer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 28, group: 'A', progLevels: { Python: 'Qabaqcıl', 'C++': 'Orta' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Araşdırma partneri'], github: 'turalai', linkedin: '' },
  { username: 'aydan.ops', name: 'Aydan Cabbarova', bio: 'Platform engineer. Kubernetes, ArgoCD, GitOps. Infrastructure as Code həvəskarı.', profession: 'Platform Engineer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 27, group: 'A', progLevels: { Go: 'Orta', Python: 'Orta', Bash: 'Qabaqcıl' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Əməkdaşlıq', 'Open Source'], github: 'aydanops', linkedin: '' },
  { username: 'samir.arch', name: 'Samir Kazımov', bio: 'Software architect. Domain-driven design, event sourcing, CQRS. 8 il təcrübə.', profession: 'Software Architect', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 35, group: 'A', progLevels: { 'C#': 'Qabaqcıl', Java: 'Qabaqcıl', TypeScript: 'Orta', SQL: 'Qabaqcıl' }, langLevels: { İngilis: 'Qabaqcıl', Türk: 'Qabaqcıl' }, lookingFor: ['Mentorluq'], github: 'samirarch', linkedin: '' },

  // ═══════════════════════════════════════════════════════
  // GROUP B — Active (40 nəfər)
  // ═══════════════════════════════════════════════════════
  { username: 'vusal.js', name: 'Vüsal Kərimov', bio: 'Node.js backend developer. Express, NestJS, MongoDB.', profession: 'Backend Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 25, group: 'B', progLevels: { JavaScript: 'Qabaqcıl', TypeScript: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: 'vusaljs', linkedin: '' },
  { username: 'sevinc.web', name: 'Sevinc Mirzəyeva', bio: 'Web developer. HTML, CSS, JavaScript — responsive dizayn.', profession: 'Web Developer', country: 'Azərbaycan', city: 'Sumqayıt', gender: 'q', age: 22, group: 'B', progLevels: { JavaScript: 'Orta', 'HTML/CSS': 'Qabaqcıl' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'ilkin.py', name: 'İlkin Həsənzadə', bio: 'Python developer. Django, FastAPI, data processing scriptləri.', profession: 'Python Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 24, group: 'B', progLevels: { Python: 'Qabaqcıl', SQL: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'ilkinpy', linkedin: '' },
  { username: 'gulay.react', name: 'Gülay Axundova', bio: 'React developer. State management, performance optimization, testing.', profession: 'Frontend Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 26, group: 'B', progLevels: { JavaScript: 'Qabaqcıl', TypeScript: 'Qabaqcıl' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Əməkdaşlıq'], github: 'gulayreact', linkedin: '' },
  { username: 'cavid.net', name: 'Cavid Əsgərov', bio: 'ASP.NET Core developer. REST API, Entity Framework, Azure.', profession: '.NET Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 28, group: 'B', progLevels: { 'C#': 'Qabaqcıl', SQL: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'cavidnet', linkedin: '' },
  { username: 'lamiya.ml', name: 'Lamiyə Sadıqova', bio: 'Junior ML engineer. Scikit-learn, pandas, data visualization.', profession: 'ML Engineer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 23, group: 'B', progLevels: { Python: 'Orta', SQL: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner', 'Mentorluq'], github: 'lamiyaml', linkedin: '' },
  { username: 'hasan.go', name: 'Həsən Allahverdiyev', bio: 'Go developer. Microservices, gRPC, Protocol Buffers.', profession: 'Backend Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 30, group: 'B', progLevels: { Go: 'Qabaqcıl', Python: 'Orta' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Əməkdaşlıq'], github: 'hasango', linkedin: '' },
  { username: 'konul.sec', name: 'Könül Əhmədli', bio: 'Security analyst. SOC operations, SIEM, incident response.', profession: 'Security Analyst', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 27, group: 'B', progLevels: { Python: 'Orta', Bash: 'Orta' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Security araşdırmaları'], github: '', linkedin: '' },
  { username: 'zaur.k8s', name: 'Zaur Mustafayev', bio: 'Kubernetes administrator. Helm charts, service mesh, monitoring.', profession: 'K8s Admin', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 29, group: 'B', progLevels: { Go: 'Orta', Bash: 'Qabaqcıl', Python: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'zaurk8s', linkedin: '' },
  { username: 'ayten.ux', name: 'Aytən Nəzərli', bio: 'UX researcher. User interviews, usability testing, A/B testing.', profession: 'UX Researcher', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 25, group: 'B', progLevels: { 'HTML/CSS': 'Orta' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Dizayn müzakirəsi'], github: '', linkedin: '' },
  { username: 'daniel.ts', name: 'Daniel Yılmaz', bio: 'TypeScript enthusiast. Deno, Bun, edge computing. Performance matters.', profession: 'Software Engineer', country: 'Türkiyə', city: 'İstanbul', gender: 'k', age: 27, group: 'B', progLevels: { TypeScript: 'Qabaqcıl', JavaScript: 'Qabaqcıl', Rust: 'Başlanğıc' }, langLevels: { İngilis: 'Qabaqcıl', Türk: 'Qabaqcıl' }, lookingFor: ['Open Source'], github: 'danielts', linkedin: '' },
  { username: 'nuray.vue', name: 'Nuray Qasımova', bio: 'Vue.js developer. Nuxt, Pinia, Tailwind CSS ilə modern web apps.', profession: 'Frontend Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 24, group: 'B', progLevels: { JavaScript: 'Qabaqcıl', TypeScript: 'Orta', 'HTML/CSS': 'Qabaqcıl' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: 'nurayvue', linkedin: '' },
  { username: 'orkhan.dba', name: 'Orxan Sultanov', bio: 'Database administrator. Oracle, PostgreSQL, performance tuning, backup strategies.', profession: 'DBA', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 34, group: 'B', progLevels: { SQL: 'Qabaqcıl', Python: 'Orta', Bash: 'Orta' }, langLevels: { İngilis: 'Orta', Rus: 'Qabaqcıl' }, lookingFor: ['Əməkdaşlıq'], github: '', linkedin: '' },
  { username: 'emma.swift', name: 'Emma Johnson', bio: 'iOS developer. SwiftUI, Combine, Core Data. Building delightful mobile experiences.', profession: 'iOS Developer', country: 'ABŞ', city: 'San Francisco', gender: 'q', age: 28, group: 'B', progLevels: { Swift: 'Qabaqcıl', Kotlin: 'Başlanğıc' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Əməkdaşlıq'], github: 'emmaswift', linkedin: '' },
  { username: 'nihad.php', name: 'Nihad Qəhrəmanov', bio: 'PHP developer. Laravel, Symfony, WordPress. E-commerce solutions.', profession: 'PHP Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 26, group: 'B', progLevels: { PHP: 'Qabaqcıl', JavaScript: 'Orta', SQL: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'nihadphp', linkedin: '' },
  { username: 'sevda.test', name: 'Sevda Rzayeva', bio: 'Test automation engineer. Selenium, Pytest, Jenkins CI/CD.', profession: 'QA Automation', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 25, group: 'B', progLevels: { Python: 'Orta', JavaScript: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: 'sevdatest', linkedin: '' },
  { username: 'fuad.arch', name: 'Fuad İbrahimov', bio: 'Cloud architect. AWS Solutions Architect. Multi-cloud strategies.', profession: 'Cloud Architect', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 36, group: 'B', progLevels: { Python: 'Orta', Go: 'Orta', Bash: 'Qabaqcıl' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Mentorluq'], github: 'fuadarch', linkedin: '' },
  { username: 'yusif.cpp', name: 'Yusif Bağırov', bio: 'C++ developer. Game engines, real-time systems, OpenGL.', profession: 'C++ Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 27, group: 'B', progLevels: { 'C++': 'Qabaqcıl', Python: 'Orta' }, langLevels: { İngilis: 'Orta', Rus: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'yusifcpp', linkedin: '' },
  { username: 'fatima.ds', name: 'Fatimə Kərimli', bio: 'Data analyst turned data scientist. SQL, Tableau, Python.', profession: 'Data Analyst', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 24, group: 'B', progLevels: { Python: 'Orta', SQL: 'Qabaqcıl' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'ali.linux', name: 'Əli Cəfərov', bio: 'Linux system administrator. Ansible, Docker, shell scripting.', profession: 'SysAdmin', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 31, group: 'B', progLevels: { Bash: 'Qabaqcıl', Python: 'Orta' }, langLevels: { İngilis: 'Orta', Rus: 'Qabaqcıl' }, lookingFor: ['Əməkdaşlıq'], github: 'alilinux', linkedin: '' },
  { username: 'nisa.figma', name: 'Nisa Əlizadə', bio: 'UI designer. Figma, Adobe XD, design tokens, component libraries.', profession: 'UI Designer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 23, group: 'B', progLevels: { 'HTML/CSS': 'Orta', JavaScript: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Dizayn müzakirəsi'], github: '', linkedin: '' },
  { username: 'lucas.node', name: 'Lucas Silva', bio: 'Node.js developer from Brazil. GraphQL, Prisma, serverless architectures.', profession: 'Backend Developer', country: 'Braziliya', city: 'São Paulo', gender: 'k', age: 26, group: 'B', progLevels: { JavaScript: 'Qabaqcıl', TypeScript: 'Qabaqcıl' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Open Source'], github: 'lucasnode', linkedin: '' },
  { username: 'javid.embed', name: 'Cavid Sadıqov', bio: 'Embedded systems developer. Arduino, ESP32, C/C++ firmware.', profession: 'Embedded Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 25, group: 'B', progLevels: { 'Arduino/C': 'Qabaqcıl', 'C++': 'Orta', Python: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'javidembed', linkedin: '' },
  { username: 'zehra.pm', name: 'Zəhra Tahirova', bio: 'Technical project manager. JIRA, Confluence, sprint planning.', profession: 'Tech PM', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 29, group: 'B', progLevels: { SQL: 'Başlanğıc', Python: 'Başlanğıc' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Əməkdaşlıq'], github: '', linkedin: '' },
  { username: 'mehdi.java', name: 'Mehdi Əlibəyov', bio: 'Java developer. Spring ecosystem, Hibernate, testing with JUnit.', profession: 'Java Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 27, group: 'B', progLevels: { Java: 'Qabaqcıl', Kotlin: 'Orta', SQL: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: 'mehdijava', linkedin: '' },
  { username: 'rana.flutter', name: 'Rana Quluzadə', bio: 'Flutter developer. Cross-platform mobile apps, Dart, state management.', profession: 'Mobile Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 24, group: 'B', progLevels: { Kotlin: 'Orta', JavaScript: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: 'ranaflutter', linkedin: '' },
  { username: 'ahmed.api', name: 'Əhməd Sadıxov', bio: 'API developer. REST, GraphQL, gRPC. API-first design philosophy.', profession: 'API Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 26, group: 'B', progLevels: { TypeScript: 'Qabaqcıl', Go: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'ahmedapi', linkedin: '' },
  { username: 'yuki.ts', name: 'Yuki Tanaka', bio: 'Full-stack TypeScript developer. Next.js, tRPC, Drizzle ORM.', profession: 'Full-stack Developer', country: 'Yaponiya', city: 'Tokyo', gender: 'q', age: 25, group: 'B', progLevels: { TypeScript: 'Qabaqcıl', JavaScript: 'Qabaqcıl', SQL: 'Orta' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Open Source'], github: 'yukits', linkedin: '' },
  { username: 'ulvi.game', name: 'Ülvi Nəzərov', bio: 'Game developer. Unity, C#, shader programming. Indie game development.', profession: 'Game Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 24, group: 'B', progLevels: { 'C#': 'Qabaqcıl', 'C++': 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'ulvigame', linkedin: '' },

  // ═══════════════════════════════════════════════════════
  // GROUP C — Normal (60 nəfər)
  // ═══════════════════════════════════════════════════════
  { username: 'parvin.css', name: 'Pərvin Qəmbərova', bio: 'CSS specialist. Animations, Grid, Flexbox.', profession: 'Frontend Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 22, group: 'C', progLevels: { 'HTML/CSS': 'Qabaqcıl', JavaScript: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'rovshan.ci', name: 'Rövşən Əzimov', bio: 'CI/CD specialist. GitHub Actions, GitLab CI, Jenkins.', profession: 'DevOps Engineer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 28, group: 'C', progLevels: { Bash: 'Qabaqcıl', Python: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'rovshanci', linkedin: '' },
  { username: 'sahil.dart', name: 'Sahil Novruzov', bio: 'Dart developer. Flutter widgets, state management.', profession: 'Mobile Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 23, group: 'C', progLevels: { Kotlin: 'Orta', JavaScript: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'elvira.sql', name: 'Elvira Əliyeva', bio: 'SQL developer. Complex queries, stored procedures, ETL.', profession: 'Data Engineer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 27, group: 'C', progLevels: { SQL: 'Qabaqcıl', Python: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: '', linkedin: '' },
  { username: 'kenan.devops', name: 'Kənan Fərhadov', bio: 'DevOps practitioner. Docker, Terraform, monitoring.', profession: 'DevOps', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 26, group: 'C', progLevels: { Python: 'Orta', Bash: 'Orta', Go: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: 'kenandevops', linkedin: '' },
  { username: 'lale.design', name: 'Lalə Cəfərova', bio: 'Graphic designer exploring web development.', profession: 'Graphic Designer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 24, group: 'C', progLevels: { 'HTML/CSS': 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Dizayn müzakirəsi'], github: '', linkedin: '' },
  { username: 'rafael.api', name: 'Rafael Suleymanov', bio: 'API integration specialist. RESTful services, webhooks.', profession: 'Integration Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 29, group: 'C', progLevels: { JavaScript: 'Orta', Python: 'Orta' }, langLevels: { İngilis: 'Orta', Rus: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: '', linkedin: '' },
  { username: 'gunay.learn', name: 'Günay Nəcəfli', bio: 'Proqramlaşdırma öyrənirəm. Python ilə başladım.', profession: 'Tələbə', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 20, group: 'C', progLevels: { Python: 'Başlanğıc' }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: ['Study partner', 'Mentorluq'], github: '', linkedin: '' },
  { username: 'emin.ruby', name: 'Emin Qasımov', bio: 'Ruby on Rails developer. REST APIs, TDD, PostgreSQL.', profession: 'Ruby Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 30, group: 'C', progLevels: { Python: 'Orta', SQL: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'eminruby', linkedin: '' },
  { username: 'xatire.tech', name: 'Xatirə İsrafilova', bio: 'Tech blogger. Texnologiya yenilikləri haqqında yazıram.', profession: 'Tech Writer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 25, group: 'C', progLevels: { 'HTML/CSS': 'Başlanğıc', Python: 'Başlanğıc' }, langLevels: { İngilis: 'Orta', Türk: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'babek.c', name: 'Babək Novruzov', bio: 'C programmer. Systems programming, OS internals.', profession: 'Systems Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 32, group: 'C', progLevels: { 'C++': 'Qabaqcıl', Bash: 'Orta' }, langLevels: { İngilis: 'Orta', Rus: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'babekc', linkedin: '' },
  { username: 'samira.iot', name: 'Samirə Hümmətova', bio: 'IoT developer. Raspberry Pi, sensor networks, MQTT.', profession: 'IoT Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 26, group: 'C', progLevels: { Python: 'Orta', 'Arduino/C': 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: '', linkedin: '' },
  { username: 'tabriz.gcp', name: 'Təbriz Vəliyev', bio: 'GCP certified cloud engineer. BigQuery, Cloud Functions.', profession: 'Cloud Engineer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 28, group: 'C', progLevels: { Python: 'Orta', Go: 'Başlanğıc', SQL: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: 'tabrizgcp', linkedin: '' },
  { username: 'maya.motion', name: 'Maya Əsgərova', bio: 'Motion designer. After Effects, Lottie animations, micro-interactions.', profession: 'Motion Designer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 23, group: 'C', progLevels: { 'HTML/CSS': 'Başlanğıc', JavaScript: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Dizayn müzakirəsi'], github: '', linkedin: '' },
  { username: 'anar.scala', name: 'Anar Məmmədzadə', bio: 'Scala developer. Functional programming, Akka, Spark.', profession: 'Scala Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 31, group: 'C', progLevels: { Java: 'Qabaqcıl', SQL: 'Orta' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Əməkdaşlıq'], github: 'anarscala', linkedin: '' },
  { username: 'dilara.pm', name: 'Dilarə Namazova', bio: 'Junior project manager. Agile öyrənirəm.', profession: 'Junior PM', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 22, group: 'C', progLevels: { }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner', 'Mentorluq'], github: '', linkedin: '' },
  { username: 'tarlan.wp', name: 'Tarlan Hüseynov', bio: 'WordPress developer. Custom themes, plugins, WooCommerce.', profession: 'WordPress Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 27, group: 'C', progLevels: { PHP: 'Orta', JavaScript: 'Orta', 'HTML/CSS': 'Qabaqcıl' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: '', linkedin: '' },
  { username: 'nargiz.bi', name: 'Nərgiz Baxşəliyeva', bio: 'Business intelligence analyst. Power BI, Tableau, SQL.', profession: 'BI Analyst', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 26, group: 'C', progLevels: { SQL: 'Qabaqcıl', Python: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'max.kotlin', name: 'Max Weber', bio: 'Android developer. Kotlin, Jetpack Compose, MVVM architecture.', profession: 'Android Developer', country: 'Almaniya', city: 'Berlin', gender: 'k', age: 27, group: 'C', progLevels: { Kotlin: 'Qabaqcıl', Java: 'Orta' }, langLevels: { İngilis: 'Qabaqcıl', Alman: 'Qabaqcıl' }, lookingFor: ['Open Source'], github: 'maxkotlin', linkedin: '' },
  { username: 'aida.teach', name: 'Aidə Həmidova', bio: 'IT müəllimi. Proqramlaşdırmanı uşaqlara öyrədirəm.', profession: 'IT Müəllimi', country: 'Azərbaycan', city: 'Lənkəran', gender: 'q', age: 29, group: 'C', progLevels: { Python: 'Orta', JavaScript: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Mentorluq'], github: '', linkedin: '' },
  { username: 'roman.elixir', name: 'Roman Kovalenko', bio: 'Elixir developer. Phoenix, LiveView, distributed systems.', profession: 'Backend Developer', country: 'Ukrayna', city: 'Kiyev', gender: 'k', age: 28, group: 'C', progLevels: { Python: 'Orta', Rust: 'Başlanğıc' }, langLevels: { İngilis: 'Qabaqcıl', Rus: 'Qabaqcıl' }, lookingFor: ['Open Source'], github: 'romanelixir', linkedin: '' },
  { username: 'rovana.web3', name: 'Rövana Həsənzadə', bio: 'Web3 developer exploring blockchain technologies.', profession: 'Web3 Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 24, group: 'C', progLevels: { JavaScript: 'Orta', TypeScript: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'namik.net', name: 'Namiq Bədəlov', bio: 'Network engineer. CCNA, firewall configuration, VPN.', profession: 'Network Engineer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 33, group: 'C', progLevels: { Bash: 'Orta', Python: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: '', linkedin: '' },
  { username: 'shams.ios', name: 'Şəms Əhmədov', bio: 'iOS developer learning SwiftUI. Building personal projects.', profession: 'iOS Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 23, group: 'C', progLevels: { Swift: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: 'shamsios', linkedin: '' },
  { username: 'ayan.writer', name: 'Ayan Miriyeva', bio: 'Technical writer. API documentation, developer guides.', profession: 'Tech Writer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 26, group: 'C', progLevels: { 'HTML/CSS': 'Orta', Python: 'Başlanğıc' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Əməkdaşlıq'], github: '', linkedin: '' },
  { username: 'huseyn.vue', name: 'Hüseyn Abdullayev', bio: 'Vue.js developer building e-commerce platforms.', profession: 'Frontend Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 25, group: 'C', progLevels: { JavaScript: 'Qabaqcıl', 'HTML/CSS': 'Qabaqcıl' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'huseynvue', linkedin: '' },
  { username: 'isa.php', name: 'İsa Məmmədli', bio: 'PHP developer. RESTful APIs, MySQL, caching strategies.', profession: 'Backend Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 28, group: 'C', progLevels: { PHP: 'Qabaqcıl', SQL: 'Orta', JavaScript: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: '', linkedin: '' },
  { username: 'narmin.ux', name: 'Nərmin Vəliyeva', bio: 'UX/UI designer. User-centered design, wireframing.', profession: 'UX/UI Designer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 24, group: 'C', progLevels: { 'HTML/CSS': 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Dizayn müzakirəsi'], github: '', linkedin: '' },
  { username: 'ruslan.go', name: 'Ruslan Həsənov', bio: 'Go developer. CLI tools, backend services.', profession: 'Go Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 27, group: 'C', progLevels: { Go: 'Orta', Python: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'ruslango', linkedin: '' },
  { username: 'sabina.data', name: 'Sabina Əhmədova', bio: 'Data analyst. Excel, SQL, Python for data analysis.', profession: 'Data Analyst', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 23, group: 'C', progLevels: { Python: 'Orta', SQL: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'ceyhun.ml', name: 'Ceyhun Rzayev', bio: 'Machine learning enthusiast. Kaggle competitions, scikit-learn.', profession: 'ML Student', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 22, group: 'C', progLevels: { Python: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: 'ceyhunml', linkedin: '' },
  { username: 'chen.angular', name: 'Chen Wei', bio: 'Angular developer. Enterprise applications, RxJS, NgRx.', profession: 'Frontend Developer', country: 'Çin', city: 'Shanghai', gender: 'k', age: 29, group: 'C', progLevels: { TypeScript: 'Qabaqcıl', JavaScript: 'Qabaqcıl' }, langLevels: { İngilis: 'Qabaqcıl', Çin: 'Qabaqcıl' }, lookingFor: ['Open Source'], github: 'chenangular', linkedin: '' },
  { username: 'xanim.study', name: 'Xanım Əliyeva', bio: 'İnformatika tələbəsi. Proqramlaşdırmanı öyrənirəm.', profession: 'Tələbə', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 20, group: 'C', progLevels: { Python: 'Başlanğıc' }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: ['Study partner', 'Mentorluq'], github: '', linkedin: '' },
  { username: 'valeh.aws', name: 'Valəh Abbasov', bio: 'AWS engineer. Lambda, DynamoDB, CloudFormation.', profession: 'Cloud Engineer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 30, group: 'C', progLevels: { Python: 'Orta', Bash: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'valehaws', linkedin: '' },
  { username: 'aysu.react', name: 'Aysu Tahmazlı', bio: 'React developer. Hooks, context, component patterns.', profession: 'Frontend Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 25, group: 'C', progLevels: { JavaScript: 'Orta', TypeScript: 'Orta', 'HTML/CSS': 'Qabaqcıl' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'parviz.be', name: 'Pərviz Rüstəmov', bio: 'Backend developer. Building APIs with Express and PostgreSQL.', profession: 'Backend Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 26, group: 'C', progLevels: { JavaScript: 'Orta', SQL: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'parvizbe', linkedin: '' },
  { username: 'gunel.pm', name: 'Günəl Orucova', bio: 'Scrum master. Agile coaching, team facilitation.', profession: 'Scrum Master', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 28, group: 'C', progLevels: { SQL: 'Başlanğıc' }, langLevels: { İngilis: 'Qabaqcıl' }, lookingFor: ['Əməkdaşlıq'], github: '', linkedin: '' },
  { username: 'toghrul.sec', name: 'Toğrul İsmayılov', bio: 'Information security. Risk assessment, compliance.', profession: 'InfoSec Specialist', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 31, group: 'C', progLevels: { Python: 'Orta', Bash: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Security araşdırmaları'], github: '', linkedin: '' },
  { username: 'sima.css', name: 'Sima Qədimova', bio: 'CSS art və animation həvəskarı. Creative coding.', profession: 'Creative Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 22, group: 'C', progLevels: { 'HTML/CSS': 'Qabaqcıl', JavaScript: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Dizayn müzakirəsi'], github: '', linkedin: '' },
  { username: 'adnan.py', name: 'Adnan Muradov', bio: 'Python automation developer. Scripting, web scraping.', profession: 'Automation Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 25, group: 'C', progLevels: { Python: 'Orta', Bash: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: 'adnanpy', linkedin: '' },
  { username: 'firuze.qa', name: 'Firuzə Abbasova', bio: 'Manual QA engineer learning automation. Selenium basics.', profession: 'QA Engineer', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 24, group: 'C', progLevels: { Python: 'Başlanğıc', JavaScript: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner', 'Mentorluq'], github: '', linkedin: '' },
  { username: 'mubariz.fe', name: 'Mübariz Həsənli', bio: 'Frontend developer. Building web applications with modern tools.', profession: 'Frontend Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 24, group: 'C', progLevels: { JavaScript: 'Orta', 'HTML/CSS': 'Qabaqcıl' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'turkan.ds', name: 'Türkan Əlizadə', bio: 'Data science tələbəsi. Kaggle yarışmalarında iştirak edirəm.', profession: 'DS Tələbəsi', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 21, group: 'C', progLevels: { Python: 'Orta', SQL: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'vagif.net', name: 'Vaqif Sultanzadə', bio: '.NET developer. Blazor, SignalR, MAUI.', profession: '.NET Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 29, group: 'C', progLevels: { 'C#': 'Orta', SQL: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Əməkdaşlıq'], github: 'vagifnet', linkedin: '' },
  { username: 'flora.lang', name: 'Flora Məlikova', bio: 'İngilis dili öyrənirəm, tech community-yə qoşuldum.', profession: 'Dil Tələbəsi', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 21, group: 'C', progLevels: { }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'ali.k8s', name: 'Əli Əliyev', bio: 'Learning Kubernetes. Container orchestration.', profession: 'Junior DevOps', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 23, group: 'C', progLevels: { Bash: 'Orta', Python: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner', 'Mentorluq'], github: '', linkedin: '' },
  { username: 'aysel.ml', name: 'Aysel Rəhimova', bio: 'ML öyrənən tələbə. TensorFlow, Keras basics.', profession: 'Tələbə', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 21, group: 'C', progLevels: { Python: 'Orta' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'nadir.code', name: 'Nadir Tağıyev', bio: 'Self-taught developer. Building side projects.', profession: 'Junior Developer', country: 'Azərbaycan', city: 'Mingəçevir', gender: 'k', age: 22, group: 'C', progLevels: { JavaScript: 'Orta', Python: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: 'nadircode', linkedin: '' },
  { username: 'afet.ux', name: 'Afət Qurbanova', bio: 'UX student. Learning design thinking, user research.', profession: 'UX Tələbəsi', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 21, group: 'C', progLevels: { 'HTML/CSS': 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Dizayn müzakirəsi', 'Mentorluq'], github: '', linkedin: '' },
  { username: 'tunc.java', name: 'Tunç Məmmədov', bio: 'Java learner. Object-oriented programming, Spring basics.', profession: 'Junior Java Dev', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 23, group: 'C', progLevels: { Java: 'Orta', SQL: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'arzu.html', name: 'Arzu Məhərrəmova', bio: 'HTML/CSS öyrənirəm. İlk veb saytımı qururam.', profession: 'Tələbə', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 20, group: 'C', progLevels: { 'HTML/CSS': 'Başlanğıc' }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: ['Study partner', 'Mentorluq'], github: '', linkedin: '' },

  // ═══════════════════════════════════════════════════════
  // GROUP D — Low Activity (32 nəfər)
  // ═══════════════════════════════════════════════════════
  { username: 'tahir.c', name: 'Tahir Əliyev', bio: 'C proqramçı. Universitetdə dərs keçirəm.', profession: 'Müəllim', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 40, group: 'D', progLevels: { 'C++': 'Qabaqcıl' }, langLevels: { İngilis: 'Orta', Rus: 'Qabaqcıl' }, lookingFor: [], github: '', linkedin: '' },
  { username: 'kamila.new', name: 'Kamilə Cəfərli', bio: 'Yeni başlayan developer. Python öyrənirəm.', profession: 'Tələbə', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 19, group: 'D', progLevels: { Python: 'Başlanğıc' }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'vugar.sql', name: 'Vüqar Əhmədov', bio: 'SQL developer. Reports, queries, database management.', profession: 'SQL Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 35, group: 'D', progLevels: { SQL: 'Qabaqcıl' }, langLevels: { İngilis: 'Orta' }, lookingFor: [], github: '', linkedin: '' },
  { username: 'simara.art', name: 'Simara Kərimova', bio: 'Digital artist interested in tech.', profession: 'Digital Artist', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 25, group: 'D', progLevels: { }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Dizayn müzakirəsi'], github: '', linkedin: '' },
  { username: 'togrul.new', name: 'Toğrul Qəhrəmanov', bio: 'Proqramlaşdırmaya yeni başlamışam.', profession: 'Tələbə', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 19, group: 'D', progLevels: { Python: 'Başlanğıc' }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'banu.learn', name: 'Banu Nəzərova', bio: 'Təzə qeydiyyatdan keçmişəm. Platformanı öyrənirəm.', profession: 'Tələbə', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 20, group: 'D', progLevels: { }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'haci.old', name: 'Hacı Hüseynov', bio: 'Yaşlı proqramçı. Pascal, Delphi zamanından.', profession: 'Retired Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 55, group: 'D', progLevels: { 'C++': 'Orta', SQL: 'Orta' }, langLevels: { İngilis: 'Başlanğıc', Rus: 'Qabaqcıl' }, lookingFor: [], github: '', linkedin: '' },
  { username: 'esmira.tech', name: 'Əsmira Quluzadə', bio: 'Texnologiya ilə maraqlanıram.', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 22, group: 'D', progLevels: { }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'ramin.dev', name: 'Ramin Xəlilov', bio: 'Junior developer. Learning the ropes.', profession: 'Junior Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 21, group: 'D', progLevels: { JavaScript: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'gulsum.new', name: 'Gülsüm Əliyeva', bio: 'Backend öyrənirəm.', profession: 'Tələbə', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 20, group: 'D', progLevels: { Python: 'Başlanğıc' }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'jale.try', name: 'Jalə Rəhimzadə', bio: 'Frontend-ə maraqlıyam.', profession: 'Tələbə', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 19, group: 'D', progLevels: { 'HTML/CSS': 'Başlanğıc' }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'fikret.try', name: 'Fikrət Bağırov', bio: 'İlk addımlarımı atıram.', profession: 'Tələbə', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 20, group: 'D', progLevels: { }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'ali.start', name: 'Əli Məmmədov', bio: 'Kompüter elmi tələbəsi.', profession: 'Tələbə', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 20, group: 'D', progLevels: { Python: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'ulker.web', name: 'Ülkər Nəsirova', bio: 'Veb sayt qurmağı öyrənmək istəyirəm.', profession: 'Tələbə', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 19, group: 'D', progLevels: { 'HTML/CSS': 'Başlanğıc' }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: ['Study partner', 'Mentorluq'], github: '', linkedin: '' },
  { username: 'elnur.dev', name: 'Elnur Həsənov', bio: 'Developer', profession: 'Developer', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 24, group: 'D', progLevels: { JavaScript: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: [], github: '', linkedin: '' },
  { username: 'vafa.code', name: 'Vəfa İbrahimova', bio: 'Kod yazmağı öyrənirəm.', profession: 'Tələbə', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 20, group: 'D', progLevels: { Python: 'Başlanğıc' }, langLevels: { İngilis: 'Orta' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'elxan.start', name: 'Elxan Səfərov', bio: 'Texnologiyaya marağım var.', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 21, group: 'D', progLevels: { }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: ['Study partner'], github: '', linkedin: '' },
  { username: 'naila.try', name: 'Nailə Vəliyeva', bio: 'Platformanı kəşf edirəm.', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 20, group: 'D', progLevels: { }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: [], github: '', linkedin: '' },
  { username: 'jasmin.look', name: 'Jasmin Həsənova', bio: 'Yeni hesab.', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 19, group: 'D', progLevels: { }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: [], github: '', linkedin: '' },
  { username: 'kamal.look', name: 'Kamal Abbasov', bio: 'Baxıram.', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 22, group: 'D', progLevels: { }, langLevels: { İngilis: 'Orta' }, lookingFor: [], github: '', linkedin: '' },
  { username: 'nurana.new', name: 'Nuranə Əliyeva', bio: 'Yeni qeydiyyat.', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 20, group: 'D', progLevels: { }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: [], github: '', linkedin: '' },
  { username: 'mirsiyab.try', name: 'Mirsiyab Hüseynov', bio: 'Test.', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 23, group: 'D', progLevels: { }, langLevels: {}, lookingFor: [], github: '', linkedin: '' },
  { username: 'shirin.look', name: 'Şirin Bayramova', bio: 'Platformanı yoxlayıram.', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 20, group: 'D', progLevels: { }, langLevels: { İngilis: 'Başlanğıc' }, lookingFor: [], github: '', linkedin: '' },
  { username: 'rovshan.look', name: 'Rövşən Hüseynov', bio: '', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 24, group: 'D', progLevels: { }, langLevels: {}, lookingFor: [], github: '', linkedin: '' },
  { username: 'mehriban.new', name: 'Mehriban Yusifova', bio: '', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 21, group: 'D', progLevels: { }, langLevels: {}, lookingFor: [], github: '', linkedin: '' },
  { username: 'tural.look', name: 'Tural Əliyev', bio: '', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 22, group: 'D', progLevels: { }, langLevels: {}, lookingFor: [], github: '', linkedin: '' },
  { username: 'gular.test', name: 'Gülar Həsənova', bio: '', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 20, group: 'D', progLevels: { }, langLevels: {}, lookingFor: [], github: '', linkedin: '' },
  { username: 'selim.check', name: 'Səlim Qədirov', bio: '', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 23, group: 'D', progLevels: { }, langLevels: {}, lookingFor: [], github: '', linkedin: '' },
  { username: 'ilaha.new', name: 'İlahə Abbasova', bio: '', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 19, group: 'D', progLevels: { }, langLevels: {}, lookingFor: [], github: '', linkedin: '' },
  { username: 'sanan.test', name: 'Sənən Məmmədov', bio: '', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'k', age: 21, group: 'D', progLevels: { }, langLevels: {}, lookingFor: [], github: '', linkedin: '' },
  { username: 'amina.silent', name: 'Əminə Rəhimova', bio: '', profession: '', country: 'Azərbaycan', city: 'Bakı', gender: 'q', age: 20, group: 'D', progLevels: { }, langLevels: {}, lookingFor: [], github: '', linkedin: '' },
];

// Demo istifadəçilər siyahısı — açar hesablar (demo login üçün)
export const DEMO_ACCOUNTS = [
  'turan.dev', 'ayla.codes', 'kamran.dev', 'nermin.ui', 'muradsec',
  'leyla.data', 'sara.design', 'elvin.backend', 'orxan.cloud', 'tural.ai',
];
